# ################################################################################################
#
#    ██╗████████╗███████╗███╗   ███╗██╗   ██╗ ██████╗ ██████╗ ███╗   ██╗███████╗██╗ ██████╗
#    ██║╚══██╔══╝██╔════╝████╗ ████║╚██╗ ██╔╝██╔════╝██╔═══██╗████╗  ██║██╔════╝██║██╔════╝
#    ██║   ██║   ███████╗██╔████╔██║ ╚████╔╝ ██║     ██║   ██║██╔██╗ ██║█████╗  ██║██║  ███╗
#    ██║   ██║   ╚════██║██║╚██╔╝██║  ╚██╔╝  ██║     ██║   ██║██║╚██╗██║██╔══╝  ██║██║   ██║
#    ██║   ██║   ███████║██║ ╚═╝ ██║   ██║   ╚██████╗╚██████╔╝██║ ╚████║██║     ██║╚██████╔╝
#    ╚═╝   ╚═╝   ╚══════╝╚═╝     ╚═╝   ╚═╝    ╚═════╝ ╚═════╝ ╚═╝  ╚═══╝╚═╝     ╚═╝ ╚═════╝
#
#      Contact: @itsme-to
#      Support: https://itsme.to/discord
#      Documentation: https://docs.itsme.to/itsmyconfig
#
# ################################################################################################

# Enable debug mode. This will enable debug logging and other debug features.
debug: false

# The symbol prefix to use for the config.
# This is used to identify the config symbols in the code.
symbol-prefix: $

listeners:
  PacketEvents:
    priority: 0
  ProtocolLib:
    priority: 1
    cache-processors: false # Not recommended (buggy), but will improve performance with ProtocolLib if it works right for you.

messages:
  invalid-use:
    - "<red><bold>ERROR</bold></red> <white>┃ Invalid use"
    - "  <yellow>/<usage>"
  reload:
    - "<green><bold>SUCCES</bold></green> <white>┃ ItsmyConfig reloaded !"
  no-permission:
    - "<red><bold>ERROR</bold></red> <white>┃ You don't have permission"
  message-sent:
    - "<green><bold>SUCCES</bold></green> <white>┃ Message Sent !"

formatting:
  thousands: k
  millions: M
  billions: B
  trillions: T
  quadrillions: Q
