# ################################################################################################
#
#    ██╗████████╗███████╗███╗   ███╗██╗   ██╗ ██████╗ ██████╗ ███╗   ██╗███████╗██╗ ██████╗
#    ██║╚══██╔══╝██╔════╝████╗ ████║╚██╗ ██╔╝██╔════╝██╔═══██╗████╗  ██║██╔════╝██║██╔════╝
#    ██║   ██║   ███████╗██╔████╔██║ ╚████╔╝ ██║     ██║   ██║██╔██╗ ██║█████╗  ██║██║  ███╗
#    ██║   ██║   ╚════██║██║╚██╔╝██║  ╚██╔╝  ██║     ██║   ██║██║╚██╗██║██╔══╝  ██║██║   ██║
#    ██║   ██║   ███████║██║ ╚═╝ ██║   ██║   ╚██████╗╚██████╔╝██║ ╚████║██║     ██║╚██████╔╝
#    ╚═╝   ╚═╝   ╚══════╝╚═╝     ╚═╝   ╚═╝    ╚═════╝ ╚═════╝ ╚═╝  ╚═══╝╚═╝     ╚═╝ ╚═════╝
#
#      Contact: @itsme-to
#      Support: https://discord.gg/itsme-to
#      Documentation: https://docs.itsme.to/itsmyconfig
#
# ################################################################################################

# Enable debug mode. This will enable debug logging and other debug features.
debug: false

# The symbol prefix to use for the config.
# This is used to identify the config symbols in the code.
symbol-prefix: $

# The minimessage serializer to use. Can be one of:
# - JSON_PARSER - Uses the JSON parser for minimessage. This is the default, recommended and tested option.
# - MM_COPY - Uses a copied and modified minimessage parser. This is only recommended if it somehow works perfectly for you.
# DO NOT CHANGE THIS UNLESS YOU KNOW WHAT YOU ARE DOING.
minimessage-serializer: MM_COPY

listeners:
  PacketEvents:
    priority: 0
  ProtocolLib:
    priority: 1
    cache-processors: false # Not recommended (buggy), but will improve performance with ProtocolLib if it works right for you.

messages:
  invalid-use:
    - "<red><bold>ERROR</bold></red> <white>┃ Invalid use"
    - "  <yellow>/<usage>"
  reload:
    - "<green><bold>SUCCES</bold></green> <white>┃ ItsmyConfig reloaded !"
  no-permission:
    - "<red><bold>ERROR</bold></red> <white>┃ You don't have permission"
  message-sent:
    - "<green><bold>SUCCES</bold></green> <white>┃ Message Sent !"

formatting:
  thousands: k
  millions: M
  billions: B
  trillions: T
  quadrillions: Q
