#CI
name: Build ✨ ItsMyConfig ✨

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v4

    # Cache Gradle dependencies and wrapper (skip for pull requests)
    - name: Cache Gradle dependencies
      uses: actions/cache@v4
      if: github.event_name != 'pull_request'
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Create Gradle Wrapper
      run: gradle wrapper

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0

    - name: Build & Test
      run: ./gradlew shadowJar

    - name: Summarize Failed Tests
      if: failure()
      run: |
        echo "## ❌ Failed Tests Summary" >> $GITHUB_STEP_SUMMARY

        REPO_URL="https://github.com/Itsme-to/ItsMyConfig/blob/main"
        TEST_SRC="core/src/test/java"

        declare -A seen

        find core/build/test-results/test/ -type f -name "*.xml" | while read file; do
          while IFS= read -r line; do
            if [[ "$line" == *"<testcase "* ]]; then
              class=$(echo "$line" | sed -n 's/.*classname="\([^"]*\)".*/\1/p')
              method=$(echo "$line" | sed -n 's/.*name="\([^"]*\)".*/\1/p')
            elif [[ "$line" == *"<failure "* ]]; then
              type=$(echo "$line" | sed -n 's/.*type="\([^"]*\)".*/\1/p')
              msg=$(echo "$line" | sed -n 's/.*message="\([^"]*\)".*/\1/p')
              msg=${msg:-"(no message)"}

              filepath="${TEST_SRC}/${class//.//}.java"
              url="$REPO_URL/$filepath"

              if [[ -z "${seen[$class]}" ]]; then
                echo "" >> $GITHUB_STEP_SUMMARY
                echo "#### [$class]($url)" >> $GITHUB_STEP_SUMMARY
                seen[$class]=1
              fi

              if [[ "$type" == "org.opentest4j.AssertionFailedError" ]]; then
                echo "- **$method** → $msg" >> $GITHUB_STEP_SUMMARY
              else
                echo "- **$method** → $type: $msg" >> $GITHUB_STEP_SUMMARY
              fi
            fi
          done < "$file"
        done
 
    - name: Extract version and commit hash
      run: |
        echo "PLUGIN_VERSION=$(grep 'version =' build.gradle | awk -F'\"' '{print $2}')" >> $GITHUB_ENV
        echo "COMMIT_HASH=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV

    - name: Upload JAR
      uses: actions/upload-artifact@v4
      with:
        name: itsmyconfig-${{ env.PLUGIN_VERSION }}-${{ env.COMMIT_HASH }}
        path: core/build/libs/*.jar
        retention-days: 30
