#CI
name: Build ✨ ItsMyConfig ✨

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v4

    # Cache Gradle dependencies and wrapper (skip for pull requests)
    - name: Cache Gradle dependencies
      uses: actions/cache@v4
      if: github.event_name != 'pull_request'
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Create Gradle Wrapper
      run: gradle wrapper

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0

    - name: Build & Test
      run: ./gradlew shadowJar

    - name: Debug Failed Test Extraction
      if: always()
      shell: bash
      run: |
        echo "🔍 Testing extraction from XML..."

        file="core/build/test-results/test/TEST-to.itsme.itsmyconfig.util.StringsTest.xml"
        echo "Processing file: $file"

        count=$(xmllint --xpath 'count(//testcase[failure])' "$file" 2>/dev/null || echo 0)
        echo "Found $count failing testcases"

        if (( count == 0 )); then
          echo "❌ No <failure> tags found in XML"
          exit 0
        fi

        for index in $(seq 1 "$count"); do
          class=$(xmllint --xpath "string((//testcase[failure])[${index}]/@classname)" "$file" 2>/dev/null)
          method=$(xmllint --xpath "string((//testcase[failure])[${index}]/@name)" "$file" 2>/dev/null)
          failure=$(xmllint --xpath "string((//testcase[failure])[${index}]/failure)" "$file" 2>/dev/null | sed 's/&lt;/</g; s/&gt;/>/g')
          type=$(xmllint --xpath "string((//testcase[failure])[${index}]/failure/@type)" "$file" 2>/dev/null)

          echo "---"
          echo "Class   : $class"
          echo "Method  : $method"
          echo "Type    : $type"
          echo "Message : $failure"
          echo "---"
        done

    - name: Summarize Failed Tests
      if: failure()
      shell: bash
      run: |
        echo "## ❌ Failed Tests Summary" >> $GITHUB_STEP_SUMMARY

        REPO_URL="https://github.com/Itsme-to/ItsMyConfig/blob/main"
        TEST_SRC="core/src/test/java"
        declare -A seen=()

        mapfile -t files < <(find core/build/test-results/test/ -type f -name "*.xml")

        for file in "${files[@]}"; do
          count=$(xmllint --xpath 'count(//testcase[failure])' "$file" 2>/dev/null || echo 0)

          if (( count == 0 )); then
            continue
          fi

          for index in $(seq 1 "$count"); do
            class=$(xmllint --xpath "string((//testcase[failure])[${index}]/@classname)" "$file" 2>/dev/null)
            method=$(xmllint --xpath "string((//testcase[failure])[${index}]/@name)" "$file" 2>/dev/null)
            # Extract failure content safely
            failure=$(xmllint --xpath "string((//testcase[failure])[${index}]/failure)" "$file" 2>/dev/null | sed 's/&lt;/</g; s/&gt;/>/g')
            type=$(xmllint --xpath "string((//testcase[failure])[${index}]/failure/@type)" "$file" 2>/dev/null)

            [[ -z "$failure" ]] && failure="(no message)"
            [[ -z "$type" ]] && type="UnknownException"
            [[ -z "$method" ]] && method="(unknown method)"
            [[ -z "$class" ]] && class="(unknown class)"

            if [[ -z "${seen[$class]}" ]]; then
              echo "" >> $GITHUB_STEP_SUMMARY
              file_path="$TEST_SRC/${class//./\/}.java"
              echo "#### [$class]($REPO_URL/$file_path)" >> $GITHUB_STEP_SUMMARY
              seen[$class]=1
            fi

            if [[ "$type" == "org.opentest4j.AssertionFailedError" ]]; then
              echo "- **$method** → $failure" >> $GITHUB_STEP_SUMMARY
            else
              echo "- **$method** → $type: $failure" >> $GITHUB_STEP_SUMMARY
            fi
          done
        done

    - name: Extract version and commit hash
      run: |
        echo "PLUGIN_VERSION=$(grep 'version =' build.gradle | awk -F'\"' '{print $2}')" >> $GITHUB_ENV
        echo "COMMIT_HASH=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV

    - name: Upload JAR
      uses: actions/upload-artifact@v4
      with:
        name: itsmyconfig-${{ env.PLUGIN_VERSION }}-${{ env.COMMIT_HASH }}
        path: core/build/libs/*.jar
        retention-days: 30
